apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-ingress-rule
  namespace: frontend
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:certificate/${{ secrets.ACM_CERTIFICATE_ID }}
  ingressClassName: alb
  rules:
    - host: www.gitchang.store
      http:
        paths:
          - path: /main.jsp
            pathType: Prefix
            backend:
              service:
                name: k8s-main-svc
                port:
                  number: 80
          - path: /index.jsp
            pathType: Prefix
            backend:
              service:
                name: k8s-index-svc
                port:
                  number: 80
          - path: /signup.jsp
            pathType: Prefix
            backend:
              service:
                name: k8s-signup-svc
                port:
                  number: 80
          - path: /login.jsp
            pathType: Prefix
            backend:
              service:
                name: k8s-login-svc
                port:
                  number: 80
          - path: /order.jsp
            pathType: Prefix
            backend:
              service:
                name: k8s-order-svc
                port:
                  number: 80
          - path: /reservation.jsp
            pathType: Prefix
            backend:
              service:
                name: k8s-reservation-svc
                port:
                  number: 80
          - path: /reservation_info.jsp
            pathType: Prefix
            backend:
              service:
                name: k8s-reservationinfo-svc
                port:
                  number: 80
