# main-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-k8smain
  namespace: backend # backend namespace에 volume 생성
spec:
  capacity:
    storage: 5Gi # 용량: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # 모든 데이터 플레인들이 읽고 쓸 수 있음.
  persistentVolumeReclaimPolicy: Retain # EFS의 file system id와 연결하므로 Retain 정책 설정
  storageClassName: efs-sc # storageclass.yaml file에서 정의
  csi:
    driver: efs.csi.aws.com # efs-csi-driver 설치
    volumeHandle: fs-03238924502102f77 # file system ID
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-k8smain
  namespace: backend # PersistentVolumeClaim 역시 같은 namespace에 생성
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
# index-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-k8sindex
  namespace: backend # backend namespace에 volume 생성
spec:
  capacity:
    storage: 5Gi # 용량: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # 모든 데이터 플레인들이 읽고 쓸 수 있음.
  persistentVolumeReclaimPolicy: Retain # EFS의 file system id와 연결하므로 Retain 정책 설정
  storageClassName: efs-sc # storageclass.yaml file에서 정의
  csi:
    driver: efs.csi.aws.com # efs-csi-driver 설치
    volumeHandle: fs-03238924502102f77 # file system ID
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-k8sindex
  namespace: backend # PersistentVolumeClaim 역시 같은 namespace에 생성
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
# sign-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-k8ssignup
  namespace: backend
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-03238924502102f77

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-k8ssignup
  namespace: backend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

---
# login-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-k8slogin
  namespace: backend
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-03238924502102f77
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-k8slogin
  namespace: backend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-k8sorder
  namespace: backend
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-03238924502102f77
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-k8sorder
  namespace: backend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-k8sreservation
  namespace: backend
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-03238924502102f77
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-k8sreservation
  namespace: backend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-k8sreservationinfo
  namespace: backend
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-03238924502102f77
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-k8sreservationinfo
  namespace: backend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
